server.port=8080
server.compression.mime-types=application/json,text/plain
server.compression.min-response-size=2048
spring.datasource.url=jdbc:postgresql://172.21.26.4:5432/postgres?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=cnitin
spring.datasource.driver-class-name=org.postgresql.Driver
